### GET /api/products/
GET http://localhost:3000/api/products/

### GET /api/products/:id
GET http://localhost:3000/api/products/2

### GET /api/products/:id error
GET http://localhost:3000/api/products/999

### POST /api/products/
POST http://localhost:3000/api/products/
content-type: application/json

{
    "product_name": "test5",
    "description": "test description asd",
    "price": 100.00,
    "image_url": "test"
}

### POST /api/products/ error
POST http://localhost:3000/api/products/
content-type: application/json

{
    "description": "test description",
    "price": 100.00,
    "image_url": "test"
}


### PUT /api/products/
PUT http://localhost:3000/api/products/2
content-type: application/json

{
    "product_name": "test_edit 67",
    "description": "test description asd",
    "image_url": "3 aaaadwqaa"
}

### DELETE /api/products/
DELETE http://localhost:3000/api/products/7

### DELETE /api/products/ error
DELETE http://localhost:3000/api/products/999

### POST login
POST http://localhost:3000/api/auth/login
content-type: application/json

{
    "email": "test@metropolia.fi",
    "password": "test"
}

### GET my user info
GET http://localhost:3000/api/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlcnJvciI6InByb21pc2VQb29sIGlzIG5vdCBkZWZpbmVkIiwiaWF0IjoxNzAxNjc4NDY3LCJleHAiOjE3MDE3NjQ4Njd9.oljHdX3KLX3hV98wjtoNTssc_BAt1-QrvWek-YGJUUI