### GET /api/meals/
GET http://localhost:3000/api/meals/

### GET /api/meals/:id
GET http://localhost:3000/api/meals/1

### GET /api/meals/:id error
GET http://localhost:3000/api/meals/999

### POST /api/meals/
POST http://localhost:3000/api/meals/
content-type: application/json

{
    "product_name": "test3",
    "description": "test description",
    "price": 100.00,
    "image_url": "test"
}

### POST /api/meals/ error
POST http://localhost:3000/api/meals/
content-type: application/json

{
    "description": "test description",
    "price": 100.00,
    "image_url": "test"
}